server:
  port: 8080

roses:
  log:
    kafka: false
    trace: false
    level: error,info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  zipkin:
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1
  kafka:
    bootstrap-servers: 192.168.1.119:9092
    listener:
      type: BATCH
    producer:
      batchSize: 500

mybatis-plus:
  typeAliasesPackage: com.lxzh.smart.campus.attendance.modular.entity

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://192.168.1.201:8001/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 300  #创建连接的超时时间 单位：毫秒
        readTimeout: 3000    #处理请求的超时时间 单位：毫秒
        errorDecoder: cn.stylefeng.roses.core.feign.RosesFeignErrorDecoder
        requestInterceptors:
        - cn.stylefeng.roses.core.feign.RosesFeignHeaderProcessInterceptor

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE #为了RosesFeignHeaderProcessInterceptor
          thread:
            timeoutInMilliseconds: 2000

logging:
  level:
    com.lxzh.smart.campus.attendance.modular.consumer: DEBUG #修改为自己的feignClient所在的包